### ISSUE TITLE
Change message at the top of Playback 

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/fusebox-playbacks#27]
Is there a way to display different messages for everyone who attended a Hop from Newcastle/Preston onwards, compared to those that went before (at the London, Manchester, Brighton and Birmingham Hops)? The message at the top now reads: 

"Thanks for visiting your Story Playback: an interactive, digital version of the text you wrote in the second Design Hop canvas.

We know it can be hard to secure internal and external support for your digital plans, and the Story Playback can help you communicate the work you’ve done to others.

It’s also a place where you can ask for help with a specific area from the CAST network. We haven't added any bespoke advice yet, but we're happy to help if and when you need it!

Simply click the relevant ‘Ask for help’ button, explain what you need and our advisors will get back to you within 1-2 weeks, subject to availability."

However, this doesn't make sense for those orgs that attended previous Hops, where we offered feedback proactively. Is there a way to change the message for them to just say "It’s also a place where you can ask for help with a specific area from the CAST network. **If we** haven't added any bespoke advice yet, we're happy to help if and when you need it!" ?

Alternatively, could just change this text for all users so that it's consistent and simple :)

**Comment by suninthesky** [comment]
Yes - important to remember the tool as it stands allows the structure of playbacks to be almost entirely changed. For example (when logged in):

1. Find the playback you want to have a different message.
2. Click `Edit`.
3. Write your new message in the grey box.

It currently doesn't look like playbacks which are automatically generated have a welcome message added. if there is a common message per `Source` then the quickest way might be to update the records directly via the command line.
