### ISSUE TITLE
Add playback link in to Airtable

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/fusebox-playbacks#28]
For existing contacts that haven't had a draft Playback created for them, is there an easy way to automatically add their unique playback link back into Airtable (in the 'playback' field) once it's created by the script/transcriber or must this be done manually?

Or at very least a view in Fusebox-Playbacks that shows all the corresponding links for each contact in one go (e.g. in the main table view, alongside their Name, Number of Comments and Source), rather than having to manually go in to each contact's view and copying the URL?

**Comment by suninthesky** [comment]
Quickest thing we can do is to export the data as a CSV or similar to reconcile manually - would that work?
