### ISSUE TITLE
Email notification sent to Playback#email when new comment added

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/fusebox-playbacks#7]
- [x] To `Playback#email` and BCC designhops@... [here](https://github.com/TechforgoodCAST/fusebox-playbacks/blob/master/app/mailers/comments_mailer.rb)
- [x] Add mailer test (similar to [this](https://github.com/TechforgoodCAST/fusebox-insights/blob/master/test/mailers/notifications_mailer_test.rb))
- [ ] Add tests to verify send (can assert against `ActionMailer::Base.deliveries`)

**Comment by itedwards** [comment]
Resolved with #19
